import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms & Conditions — Dayli AI',
  description: 'The terms that govern your use of Dayli AI.',
}

export default function TermsPage() {
  return (
    <div className="flex min-h-screen w-full flex-col font-sans bg-white">
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[60] focus:rounded-lg focus:bg-[#461F65] focus:px-4 focus:py-2 focus:text-white focus:font-semibold focus:shadow-lg"
      >
        Skip to main content
      </a>

      <header className="flex h-[72px] shrink-0 items-center justify-between border-b border-gray-100 bg-white/80 px-6 md:px-12 backdrop-blur-md sticky top-0 z-50">
        <Link href="/" className="transition-transform hover:scale-105 focus-visible:outline-2 focus-visible:outline-[#461F65] focus-visible:outline-offset-2 rounded">
          <img src="/dayli-logotype.png" alt="Dayli AI" className="h-8 md:h-9 object-contain" />
        </Link>
      </header>

      <main id="main-content" tabIndex={-1} className="flex-1 max-w-3xl mx-auto w-full px-4 py-12 focus:outline-none">
        <h1 className="font-serif text-3xl md:text-4xl font-bold text-[#461F65] mb-2">
          Terms &amp; Conditions
        </h1>
        <p className="text-sm text-[#461F65]/70 mb-8">
          Last Updated: May 2, 2026
        </p>

        <div className="text-[#461F65]/80 leading-relaxed space-y-6 text-[15px]">
          <section>
            <p>
              These Terms &amp; Conditions are being finalized. While the full document
              is being prepared, the following short summary explains what to expect
              when using Dayli AI today.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[#461F65] mb-2">
              Use of the Service
            </h2>
            <p>
              Dayli AI is a community-driven service that helps people find adaptive
              solutions for daily living. You may use it for personal, non-commercial
              purposes. Please do not misuse the service, attempt to disrupt it, or use
              it in a way that harms others.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[#461F65] mb-2">
              Content You Submit
            </h2>
            <p>
              Solutions, comments, and other content you contribute remain yours. By
              submitting them, you grant Dayli AI a non-exclusive license to display
              and share them within the service to support the community's mission.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[#461F65] mb-2">
              Disclaimer
            </h2>
            <p>
              Information shared by community members or generated by the AI is for
              general informational purposes only and is not medical, legal, or
              professional advice. Always consult a qualified professional for
              decisions that affect your health or safety.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[#461F65] mb-2">
              Questions
            </h2>
            <p>
              For any question about these terms, please email{' '}
              <a
                href="mailto:info@dailylivinglabs.com"
                className="text-[#9230E3] underline hover:no-underline focus-visible:outline-2 focus-visible:outline-[#9230E3] focus-visible:outline-offset-2 rounded"
              >
                info@dailylivinglabs.com
              </a>
              . We update this page as the full document is finalized.
            </p>
          </section>
        </div>
      </main>

      <footer className="bg-white border-t border-gray-100 px-6 py-12 md:py-16 text-center">
        <p className="text-[14px] text-gray-400">
          © {new Date().getFullYear()} Dayli AI. All rights reserved.
        </p>
      </footer>
    </div>
  )
}
